"use client"

import NavMenu from "../../components/NavMenu";
import "./globals.css";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";

export const metadata = {
  title: "Module-9",
  description: "Generated by create next.js & react.js app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="w-3/6 m-auto">
        <NavMenu />
        {children}

        <ProgressBar
          height="5px"
          color="#3B82F6"
          options={{ showSpinner: false }}
        />
        </div>
      </body>
    </html>
  );
}
